/**
 * Logging system for tracking AI operations and token usage.
 */
const Logger = {

  /**
   * Logs activity to the Spreadsheet specified in Script Properties.
   * @param {string} sender - Email address of the sender.
   * @param {string} status - Status of the operation (e.g., 'Processed', 'Filtered').
   * @param {number} tokens - Total tokens used for the request.
   */
  log(sender, status, tokens) {
    let ss;
    const logSheetId = CONFIG.getLogSheetId();

    try {
      if (logSheetId) {
        ss = SpreadsheetApp.openById(logSheetId);
      } else {
        // Fallback: Create a new sheet if URL is missing
        ss = SpreadsheetApp.create('MailAgent_AutoGenerated_Logs');
        console.warn('LOG_SHEET_URL not found. Created new log file: ' + ss.getUrl());
      }
      
      const sheet = ss.getSheets()[0];
      
      // Add headers if the sheet is empty
      if (sheet.getLastRow() === 0) {
        sheet.appendRow(['Date', 'Sender', 'Status', 'Tokens Used']);
      }
      
      sheet.appendRow([new Date(), sender, status, tokens]);
      
    } catch (e) {
      console.error("Logging Error: " + e.message);
      // Fallback to standard Apps Script logs if Spreadsheet is unreachable
      console.log(`Fallback Log -> Date: ${new Date()}, Sender: ${sender}, Status: ${status}, Tokens: ${tokens}`);
    }
  }
};